runtime: nodejs20

env_variables:
  MONGODB_URI: "mongodb+srv://vikaas08:3seRBT75zTeF3AgG@cluster0.isnfz.mongodb.net/HW3?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET_KEY: "bfca43c4cf1e1c01a0278c9351fdbed14670784320d31ceedce17f539bcab3c28690a5ea3bce03049d66a1f17ad60efec8bab646440ee0b15cc28abe20c094e9"
  ARTSY_CLIENT_ID: "648c33e8565fb3b34ba2"
  ARTSY_CLIENT_SECRET: "6c403bdf9fcf9a78f2cecd7701df18fe"
  ARTSY_TOKEN: "eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IiIsInN1YmplY3RfYXBwbGljYXRpb24iOiI4ZGFjZWMwNy0yOTM4LTQ2YzktODQ4YS1lYWVmYWUzYTk4ZTkiLCJleHAiOjE3NDcyNzU5MTIsImlhdCI6MTc0NjY3MTExMiwiYXVkIjoiOGRhY2VjMDctMjkzOC00NmM5LTg0OGEtZWFlZmFlM2E5OGU5IiwiaXNzIjoiR3Jhdml0eSIsImp0aSI6IjY4MWMxNjA4MzIxZWIwMmYwMzQ1NzdkMSJ9.NKC96szuqD-pJaCShj4IjFTtV_hS_ZnARwXpkoG1Jxs"
handlers:
  # - url: /assets/.*
  #   static_dir: dist/assets

  # - url: /api/.*
  #   script: auto

  # - url: /.*
  #   static_dir: dist

  # - url: /(.*\.(js|css|png|jpg|ico|svg|json|woff|woff2|ttf|map|webmanifest))
  #   static_files: dist/\1
  #   upload: dist/.*

  # Serve assets (JS, CSS, images) from dist/assets
  - url: /assets/(.*)
    static_files: dist/assets/\1
    upload: dist/assets/.*

  # Serve API calls (backend routes)
  - url: /api/.*
    script: auto

  # Serve other static files (JS, CSS, images, etc.) from dist
  - url: /(.*\.(js|css|png|jpg|ico|svg|json|woff|woff2|ttf|map|webmanifest))
    static_files: dist/\1
    upload: dist/.*

  # # Serve the React/Vite app's index.html for all other routes
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
